### ISSUE TITLE
Requirements for input data

### ISSUE THREAD

**Issue by xjallen** [joannawolthuis/MetaboShiny#47]
Hi, I'm working with another person's dataset and they only have peak tables for the positive mode. Is there any way to omit the negative mode peak table from input?

**Comment by joannawolthuis** [comment]
Hi! Good point and should be easy to implement! I'll let you know once it's pushed :)

**Comment by joannawolthuis** [comment]
This should be possible as of now (8b2bf67), please check :)

**Comment by xjallen** [comment]
Thank you for the quick turnaround! It seems to be working fantastically.
