### ISSUE TITLE
Normalization Failed Error

### ISSUE THREAD

**Issue by xjallen** [joannawolthuis/MetaboShiny#51]
I'm bringing my own data into MetaboShiny and can't seem to normalize it. I receive the error "Error in `[.data.table`(metshiCSV, , ..condition) :column(s) not found: NA"

Do you know what is causing this error to be thrown up?

**Comment by joannawolthuis** [comment]
Hi! It seems like a metadata problem, can you give an idea of what your metadata looks like?

**Comment by xjallen** [comment]
My metadata contains presence/absence data for microbial treatments as well as plant physiological responses, so a mix of both numerical and non-numerical data. These are in addition to the sample and individual columns that are required.

**Comment by joannawolthuis** [comment]
Hi there! I kind of need a dummy (maybe a scrambled?) version of your metadata to estimate what the problem is - the error is at a point where it looks for a 'default' experimental variable to use (at least 2 groups, but as few as possible) so i expect the problem is in that possibly the metadata is in a (slightly) wrong format.

**Comment by xjallen** [comment]
I've emailed you a dummy matrix. Apologies if that's inconvenient, but I couldn't think of a better way to get it to you. Thanks!

**Comment by joannawolthuis** [comment]
That's perfect, thank you! To test the fix, are you working on the Docker
ver. or on your own R version?

Op di 29 dec. 2020 om 19:08 schreef xjallen <notifications@github.com>:

**Comment by xjallen** [comment]
I am working on the R version.

**Comment by joannawolthuis** [comment]
Alright, great. Would you mind trying out the dev branch to see if it fixes your problem? I do ask for your patience, I was working on rolling it out to master branch soon so there might be some bugs (but hopefully not the one you mention here :) )

**Comment by xjallen** [comment]
I'm trying to install the dev branch, but hit an error stating "Error : (converted from warning) unable to re-encode 'oxy-wrapper_functions.R' line 1568"

**Comment by joannawolthuis** [comment]
Hmm, I tried a fix, would you mind trying again? Thanks :)

Op wo 30 dec. 2020 om 00:53 schreef xjallen <notifications@github.com>:

**Comment by xjallen** [comment]
I've got the dev branch installed, however it fails on startup. The error reads: 
       Warning: Error in list.files: invalid 'path' argument
           46: list.files
           45: <observer> [reactive/patientdbs.R#8]
           2: shiny::runApp
           1: MetaboShiny::start_metshi

**Comment by joannawolthuis** [comment]
Cannot reproduce this one, but I tried a fix, please give it a try!
Are you working on Windows? Might continue debugging on my Windows PC if so.


Op do 31 dec. 2020 om 00:13 schreef xjallen <notifications@github.com>:

**Comment by xjallen** [comment]
I am working on Windows. I'm getting a combination of errors now:
Warning: Error in [[: subscript out of bounds
  45: <observer> [D:\xvsal\R\win-library\4.0\MetaboShiny/server.R#296]
   2: shiny::runApp
   1: MetaboShiny::start_metshi
Warning: Error in dir.exists: invalid filename argument
  46: dir.exists
  45: <observer> [reactive/patientdbs.R#8]
   2: shiny::runApp
   1: MetaboShiny::start_metshi

**Comment by joannawolthuis** [comment]
Alright, thank you again! I switched to Windows and got it running properly
on that PC. Please try the dev branch again once you have time!

Op do 31 dec. 2020 om 19:35 schreef xjallen <notifications@github.com>:

**Comment by xjallen** [comment]
Ok! I've got the dev branch installed and working. Unfortunately I'm hitting errors when ingesting the data. The error reads:
[1] "Importing neg mode peaks!"
Error in peaklists[[which(isNonEmpty)]] : 
  attempt to select less than one element in get1index.

The example data included with MetaboShiny doesn't cause this error, so I'm guessing that something is wrong with my peak data...

**Comment by joannawolthuis** [comment]
I fear so yes :( in which ways does your format differ from the example?
Again dummy input data would be great for me to help, if you have it :)

**Comment by xjallen** [comment]
I don't notice any obvious differences in the format, but I could easily be wrong. I've emailed you a dummy datasheet. Thanks for all the help!

**Comment by joannawolthuis** [comment]
Thanks! I imported your data OK now. Can you try dev again? :)

Op za 2 jan. 2021 om 18:53 schreef xjallen <notifications@github.com>:

**Comment by xjallen** [comment]
I've finally gotten around to trying it out and the data are imported without errors! Normalization however does not work with my data nor the example data the error reads:

Error in colSums(mSet$dataSet$missing) : 
  'x' must be an array of at least two dimensions

**Comment by joannawolthuis** [comment]
Found the cause - my MetaboanalystR version was one behind the newest. Will
start forcing specific version soon, haha! Please take a look and let me
know.

Op do 7 jan. 2021 om 06:19 schreef xjallen <notifications@github.com>:

**Comment by xjallen** [comment]
I believe you've addressed all of my issues! All of my data are being imported properly, normalized, and analyzed! Thanks a lot!
